feat(map): merge routes model and view model
HikeMate/hikeMateApp pull request #51
Opened 2024-10-16 22:23 UTC by MaelImhof

# Summary

The map screen was created in three parts : the screen itself, the view model, and the repository. The view model and the repository had been worked on in parallel, hence one needed to put them together.

This pull request makes the map screen functional, in the sense that the user can now move around on the map and search for hikes wherever they want (see screenshots below).

To reach this objective :

- The view model `ListOfHikeRoutesViewModel.kt` was refactored to use `HikeRoute`s instead of `String`s
- The map screen was refactored to include a `Search here` button to avoid sending too many requests to the OSM API
- Tests were implemented and updated to cover the new behaviors

<img src="https://github.com/user-attachments/assets/ae760ad7-e50c-4d8a-8482-cc740dc9cb81" width="400px" />

<img src="https://github.com/user-attachments/assets/8f9ede8c-6677-454b-b028-00d686c434f4" width="400px" />

# Details

The high-level view of the changes is :

- The map now has a search button
- The user can move the map to where they want to search for hikes, then press the button
- Pressing the button will hide the button (to avoid spamming) and show a loading animation
- When the requests is finished (either succeeded or failed), the loading message disappears and the button is showed again
- If the request succeeded, found hikes are displayed in the list as before
- If the request failed, a toast is displayed to the user, indicating that there was an error

Also, all hike routes now come from the API. That is why their weird ID is displayed instead of a name, because the model does not provide a name yet.

## Side-changes

Apart from those main changes, two side-quests happened :

1. Added Mockito as an Android tests dependency (Mockito could not be used for UI testing with the previous setup, so I quickly modified `build.gradle.kts`, it works locally, I'm waiting to see the CI)
2. Removed hardcoded `Dispatchers.IO` from the view model and replaced them with an injected value, made Sonar happy and made the tests easier

## Conclusion

Please let me know if you have any questions or any changes are required (most probably).

2024-10-16 23:12 UTC, MaelImhof commented
There is one test that still needs fixing, I will see that tomorrow, for now I need some sleep. In any case, the rest of the PR is ready to be reviewed, there's only this test, `clickingOnHikeItemSelectsHikeRoute`, that needs more work.

By the way, any suggestion on how to fix it would be appreciated !

2024-10-17 14:28 UTC, MaelImhof commented
Hope this fixes the problematic test.

Apart from the test that failed, I resolved conflicts with the `main` branch by integrating :

- The navigation PR that affected the map screen (#33)
- The PR for drawing hikes on the map (#48)

This makes the current PR contain a lot of new features, maybe too many for a single PR, unfortunately it is unavoidable given that this one is the last one to get merged, and given the deadlines we are facing.

2024-10-17 17:09 UTC, mchac15 requested changes
Overall I love the code. It is very well written and seems robust enough. Maybe read at the comments I made about your code.

2024-10-17 20:27 UTC, MaelImhof commented on app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
> +            hikeRoutes_.value = routes
That's the idea yes. `hikeRoutes_` is a `MutableStateFlow`. It contains a value, the "current" value, and can be observed by UI components (with `.collectAsState()`). When we say `hikeRoutes_.value = someValue`, it sends an update event to all the listeners that "subscribed" to this state flow.

In Jetpack Compose, update events will trigger a recomposition, leading to an update of the list of hikes in the UI.

2024-10-17 20:28 UTC, MaelImhof commented on app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
> +      controller.setZoom(12.0)
Fair, I'll fix this real quick. I hope from the bottom of my heart that CI will still pass with new commits.

2024-10-17 20:43 UTC, MaelImhof commented on app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
> +      Log.d(MapScreen.LOG_TAG, "Too many hikes (${routes.size}) to display on the map")
Possible for sure, I did not think it made much sense when implementing it, but I added it in a commit I will push very soon.

2024-10-17 21:24 UTC, mchac15 approved these changes
LGTM

2024-10-17 21:39 UTC, merged