Feat/merge firebase auth with signin composable
HikeMate/hikeMateApp pull request #93
Opened 2024-10-31 14:44 UTC by davidholzwarth

# Summary

This PR merges the Firebase Authentication functionality with the SignIn UI. This means that now when pressing the sign in button, the sign in process gets triggered, as opposed to simulating a successful signin. 

The sign in UI was changed, as well as the sign in screen tests and the end to end tests.

# Details

Depends on the nature of the PR :
- **Code changes :** describe the conceptual approach taken in the code and tell the reviewer what part of the changes does what, so that it's easier to read the code
- **Other changes :** Add details if relevant, or remove this section if not useful

2024-11-04 11:35 UTC, rBergCode commented
Note: Sonar is failing here and it's normal. I removed tests in order to merge this. It will be fix soon with another PR.

2024-11-05 16:35 UTC, mchac15 reviewed
Still seems like there is some bugs in the code you need to handle. I don't know if it's a me problem. Please tell me if you don't get the same.

2024-11-05 16:35 UTC, mchac15 commented on app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
> +                    Toast.LENGTH_LONG)
Also the message seems to be too long for the toast and appears cut after some words.

2024-11-05 16:35 UTC, mchac15 commented on app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
> +                    Toast.LENGTH_LONG)
Bug: It still looks like there is an error with Google Authentication whenever I try to put my email to Sign In I get an error message saying: "This account already exists"

2024-11-05 16:36 UTC, mchac15 requested changes
Check the comments I made and get in contact if you need anything

2024-11-07 10:11 UTC, rBergCode commented on app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
> +                    "Connected Google Account to your device successfully. Please wait while we retry the signup.",
Fixed!

2024-11-07 10:12 UTC, rBergCode commented on app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
> +                    Toast.LENGTH_LONG)
This should have been fixed. Can you provide me your SH1 key from the task `signingReport` in private ?

2024-11-07 17:37 UTC, mchac15 submitted a review, later dismissed
LGTM

2024-11-07 18:34 UTC, mchac15 requested changes
One small change but then it's good.

2024-11-07 18:34 UTC, mchac15 commented on app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInScreenTest.kt
>      composeTestRule.onNodeWithTag("appIcon").assertIsDisplayed()
Duplicate here

2024-11-07 18:48 UTC, rBergCode commented on app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInScreenTest.kt
>      composeTestRule.onNodeWithTag("appIcon").assertIsDisplayed()
Good catch!

2024-11-07 19:03 UTC, Wylwi approved these changes
LGTM now. Don't forget to put tests back!

Note: @mchac15 did all the review job here. This review is not mine, just approved for timing purposes

2024-11-07 19:06 UTC, merged